name: Build

"on":
  push:
    branches:
      - main
    tags:
      - "*.*.*"
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  unit-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup workspace
        uses: ./.github/actions/setup-workspace

      - name: Run Pytest suite
        run: just pytest -vv

  generate-image-variants:
    name: Generate Image Variants
    needs: unit-tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        variant:
          - ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup workspace
        uses: ./.github/actions/setup-workspace

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt install -y jq

      - name: Build base images (${{ matrix.variant }})
        id: images
        run: |
          export SUMMARY_FILE=${{ matrix.variant }}-summary.json
          uv run imvar-cli -vv build \
            -c docker/${{ matrix.variant }} \
            -f docker/variants.yaml \
            -o "${SUMMARY_FILE}"

          JSON_DATA=$(cat "${SUMMARY_FILE}")
          TAGS=$(echo "$JSON_DATA" | jq -r '.images[]')
          echo "docker_tags<<EOF" >> $GITHUB_OUTPUT
          echo "$TAGS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Publish images
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "${{ steps.images.outputs.docker_tags }}" | while read -r tag; do
            [ -z "$tag" ] && continue
            echo "Pushing $tag"
            docker push "$tag"
          done
